set(_Iconv_ROOT_CANDIDATE "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
set(_Iconv_HEADER_CANDIDATE "${_Iconv_ROOT_CANDIDATE}/include/iconv.h")
message(STATUS "_Iconv_ROOT_CANDIDATE: ${_Iconv_ROOT_CANDIDATE}")
message(STATUS "_Iconv_HEADER_CANDIDATE: ${_Iconv_HEADER_CANDIDATE}")
if(EXISTS "${_Iconv_HEADER_CANDIDATE}")
  set(Iconv_ROOT "${_Iconv_ROOT_CANDIDATE}")
  message(STATUS "Iconv_ROOT: ${Iconv_ROOT}")
  set(_Iconv_INCLUDE_DIR_CANDIDATE "${Iconv_ROOT}/include")
  if(MSVC)
    set(_Iconv_LIBRARY_CANDIDATE "${Iconv_ROOT}/lib/iconv.lib")
  else()
    set(_Iconv_LIBRARY_CANDIDATE "${Iconv_ROOT}/lib/iconv.a")
  endif()
  if(EXISTS "${_Iconv_LIBRARY_CANDIDATE}")
    set(Iconv_LIBRARY "${_Iconv_LIBRARY_CANDIDATE}" CACHE FILEPATH "Path to vcpkg libiconv" FORCE)
    message(STATUS "Iconv_LIBRARY: ${Iconv_LIBRARY}")
  endif()
  if(EXISTS "${_Iconv_INCLUDE_DIR_CANDIDATE}")
    set(Iconv_INCLUDE_DIR "${_Iconv_INCLUDE_DIR_CANDIDATE}" CACHE PATH "Path to vcpkg iconv headers" FORCE)
    message(STATUS "Iconv_INCLUDE_DIR: ${Iconv_INCLUDE_DIR}")
  endif()
endif()
unset(_Iconv_ROOT_CANDIDATE)
unset(_Iconv_HEADER_CANDIDATE)
unset(_Iconv_INCLUDE_DIR_CANDIDATE)
unset(_Iconv_LIBRARY_CANDIDATE)
if (ICONV_REQUIRED)
  find_package(Iconv REQUIRED)
else()
  find_package(Iconv)
endif()
if(Iconv_IS_BUILT_IN)
  message(STATUS "Using built-in iconv.")
else()
  message(STATUS "Using external iconv from ${Iconv_LIBRARIES}.")
endif()
