if(NOT DEFINED required_icu_libraries)
  set(required_icu_libraries i18n uc data)
endif()
if(NOT DEFINED required_icu_version)
  set(required_icu_version 67.0)
endif()

message(STATUS "required_icu_libraries: ${required_icu_libraries}")
message(STATUS "required_icu_version: ${required_icu_version}") 

set(_ICU_ROOT_CANDIDATE "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
set(_ICU_INCLUDE_DIR_CANDIDATE "${_ICU_ROOT_CANDIDATE}/include/unicode")
if(NOT ICU_FOUND)
  if(EXISTS "${_ICU_INCLUDE_DIR_CANDIDATE}")
    set(ICU_ROOT "${_ICU_ROOT_CANDIDATE}")
    message(STATUS "ICU_ROOT: ${ICU_ROOT}.")
    list(PREPEND CMAKE_PREFIX_PATH "${ICU_ROOT}")
  endif()
  if(ICU_REQUIRED)
    find_package(ICU ${required_icu_version} COMPONENTS ${required_icu_libraries} REQUIRED)
  else()
    find_package(ICU ${required_icu_version} COMPONENTS ${required_icu_libraries})
  endif()
endif()
unset(_ICU_ROOT_CANDIDATE)
unset(_ICU_INCLUDE_DIR_CANDIDATE)

message(STATUS "ICU_FOUND: ${ICU_FOUND}")
if(ICU_FOUND)
  message(STATUS "ICU_INCLUDE_DIRS: ${ICU_INCLUDE_DIRS}")
  message(STATUS "ICU_LIBRARIES: ${ICU_LIBRARIES}")
  include_directories(BEFORE SYSTEM ${ICU_INCLUDE_DIRS})
  add_compile_definitions(HAVE_ICU=1)
endif()
